/*******************************************************************************
 * BTDecorator generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib © 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class BTDecorator extends BTNode
    abstract
    native;

/** The node we decorate */
var() const BTNode Child;