/*******************************************************************************
 * PointInSpace_TA generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib © 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class LightCurveType_TA extends Actor;

/** Value for the "Type" scalar parameter for the material */
var() int ParameterValue;