/*******************************************************************************
 * VehiclePickup_BoostModifier_Teleporter_TA generated by Eliot.UELib using UE Explorer.
 * Eliot.UELib © 2009-2015 Eliot van Uytfanghe. All rights reserved.
 * http://eliotvu.com
 *
 * All rights belong to their respective owners.
 *******************************************************************************/
class VehiclePickup_BoostModifier_Teleporter_TA extends VehiclePickup_BoostModifier_TA;